# Standards: 0.11
---

# 1.6.1.4 Ensure SETroubleshoot is not installed (Scored)

- name: 1.6.1.4 Ensure SETroubleshoot is not installed (Scored)
  yum:
    lock_timeout: 180
    name: setroubleshoot
    state: removed
  tags:
      - level-1
      - section-1
      - "1.6.1.4"
      - scored