# Standards: 0.11
---

# 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)

- name: Install the SE Linux requirements - libselinux-python
  yum:
    lock_timeout: 180
    name: libselinux-python
    state: installed

- name: Install the SE Linux requirements - policycoreutils-python
  yum:
    lock_timeout: 180
    name: policycoreutils-python
    state: installed

- name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
  selinux:
    policy: targeted
    state: enforcing
  tags:
      - level-2
      - section-1
      - "1.6.11"
      - scored
