# Standards: 0.11
---

# 4.1.18 Ensure the audit configuration is immutable (Scored)

- name: 4.1.18 Ensure the audit configuration is immutable (Scored)
  shell: |
    set -o pipefail
    grep "^\s*[^#]" {{ cis_audit_rules_filename }} | tail -1
  tags:
    - "4.1.18"
    - level-2
    - section-4
    - scored
