# Standards: 0.11
---

# 2.1.11 Ensure IMAP and POP3 server is not enabled

- name: 2.1.11 - Ensure IMAP and POP3 server is not enabled
  systemd:
    name: "dovecot"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.11"
    - scored
  when:
    - ansible_facts.services['dovecot'] is defined
