# Standards: 0.11
---

# 2.1.20 Ensure rsync service is not enabled

- name: 2.1.20 - Ensure rsync service is not enabled
  systemd:
    name: "rsyncd"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.20"
    - scored
  when:
    - ansible_facts.services['rsyncd'] is defined
