# Standards: 0.11
---

# 2.1.10 Ensure HTTP server is not enabled

- name: 2.1.10 - Ensure HTTP server is not enabled
  systemd:
    name: "httpd"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.10"
    - scored
  when:
    - ansible_facts.services['httpd'] is defined