# Standards: 0.11
---

# 2.1.17 Ensure rsh server is not enabled

- name: 2.1.17 - Ensure rsh server is not enabled
  systemd:
    name: "rsh.socket"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.17"
    - scored
  when:
    - ansible_facts.services['rsh.socket'] is defined

- name: 2.1.17 - Ensure rlogin is not enabled
  systemd:
    name: "rlogin.socket"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.17"
    - scored
  when:
    - ansible_facts.services['rlogin.socket'] is defined

- name: 2.1.17 - Ensure rexec is not enabled
  systemd:
    name: "rexec.socket"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.17"
    - scored
  when:
    - ansible_facts.services['rexec.socket'] is defined
