# Standards: 0.11
---

# 2.1.4 Ensure CUPS is not enabled

- name: 2.1.4 - Ensure CUPS is not enabled
  systemd:
    name: "cups"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.4"
    - scored
  when:
    - ansible_facts.services['cups'] is defined