# Standards: 0.11
---

# 2.1.7 Ensure NFS and RPC are not enabled

- name: 2.1.7 -  Ensure NFS is not enabled
  systemd:
    name: "slapd"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.7"
    - scored
  when:
    - ansible_facts.services['slapd'] is defined

- name: 2.1.7 -  Ensure nfs-server is not enabled
  systemd:
    name: "nfs-server"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.7"
    - scored
  when:
    - ansible_facts.services['nfs-server'] is defined

- name: 2.1.7 -  Ensure rpcbind is not enabled
  systemd:
    name: "rpcbind"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.7"
    - scored
  when:
    - ansible_facts.services['rpcbind'] is defined
