# Standards: 0.11
---

# 2.1.1.3 Ensure chrony is configured

- name: 2.1.1.3 - Check if chrony configure file exists
  stat:
    path: "{{ cis_chrony_configure_filename }}"
  register: chrony_configure_2_1_1_3
  tags:
    - level-1
    - "2.1.1.3"
    - scored

- name: 2.1.1.3 - Ensure chrony is configure
  copy:
    dest: "{{ cis_chrony_configure_filename }}"
    content: "server {{ cis_chrony_server }} prefer iburst\n"
  when: chrony_configure_2_1_1_3.stat.exists is not defined or not chrony_configure_2_1_1_3.stat.exists
  tags:
    - level-1
    - "2.1.1.3"
    - scored

- name: 2.1.1.3 - Ensure chrony is configure
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^server\\s+"
    line: "server {{ cis_chrony_server }} prefer iburst"
  when: chrony_configure_2_1_1_3.stat.exists is defined or chrony_configure_2_1_1_3.stat.exists
  tags:
    - level-1
    - "2.1.1.3"
    - scored

- name: Set Options -u chrony in  /etc/sysconfig/chronyd
  replace:
    path:  /etc/sysconfig/chronyd
    regexp: '^OPTIONS=.*$'
    replace: 'OPTIONS="-u chrony"'
  tags:
    - level-1
    - "2.1.1.3"
    - scored
