# Standards: 0.11
---

# 2.1.6 Ensure LDAP server is not enabled

- name: 2.1.6 - Ensure LDAP server is not enabled
  systemd:
    name: "slapd"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.6"
    - scored
