# Standards: 0.11
---

# 2.1.21 Ensure talk server is not enabled

- name: 2.1.21 - Ensure talk server is not enabled
  systemd:
    name: "ntalk"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.21"
    - scored
