# Standards: 0.11
---

# 2.1.5 Ensure DHCP Server is not enabled

- name: 2.1.5 - Ensure DHCP Server is not enabled
  systemd:
    name: "dhcpd"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "2.1.5"
    - scored
