# Standards: 0.11
---

# 2.2.2 Ensure rsh client is not installed

- name: 2.2.2 - Ensure rsh client is not installed
  yum:
    lock_timeout: 180
    name: rsh
    state: absent
  tags:
    - level-1
    - section-1
    - "2.2.2"
    - scored
