# Standards: 0.11
---

# 2.2.1 Ensure NIS Client is not installed

- name: 2.2.1 - Ensure NIS Client is not installed
  yum:
    lock_timeout: 180
    name: ypbind
    state: absent
  tags:
    - level-1
    - section-1
    - "2.2.1"
    - scored
