# Standards: 0.11
---

# 3.2.7 Ensure Reverse Path Filtering is enabled

- name: 3.2.7 - Ensure Reverse Path Filtering is enabled
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.7"
    - scored

- name: 3.2.7 - Ensure Reverse Path Filtering is enabled
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 1
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.7"
    - scored

- name: 3.2.7 - Ensure Reverse Path Filtering is enabledin active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.conf.all.rp_filter=1"
    - "sysctl -w net.ipv4.conf.default.rp_filter=1"
    - "sysctl -w net.ipv4.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.2.7"
    - scored
