# Standards: 0.11
---

# 3.3.1 Ensure TCP Wrappers is installed

- name: 3.3.1 - Ensure TCP Wrappers is installed
  yum:
    lock_timeout: 180
    name: "tcp_wrappers"
    state: latest
  tags:
    - level-1
    - section-3
    - "3.3.1"
    - scored
