# Standards: 0.11
---

# 5.1.1 Ensure cron daemon is enabled

- name: 5.1.1 - Ensure cron is installed
  yum:
    lock_timeout: 180
    name: cronie
    state: present
  tags:
    - level-1
    - section-5
    - "5.1.1"
    - scored

- name: 5.1.1 - Ensure cron daemon is enabled
  systemd:
    name: "crond"
    enabled: yes
    state: started
  ignore_errors: false
  tags:
    - level-1
    - section-5
    - "5.1.1"
    - scored